config/routes.rb
Rails.application.routes.draw do
  root "surveys#index"
  resources :surveys
  resources :answers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :survey
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/survey.rb
class Survey < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: %i[ show ]

  # GET /answers or /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # POST /answers or /answers.json
  def create
    @answer = Answer.new(survey_id: params[:survey_id], response: params[:response])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to root_url, notice: "Answer was successfully recorded." }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def result_percentage(survey, answer)
    total = survey.answers.count
    count = survey.answers.where(response: answer).count
    (count.to_f / total.to_f * 100).round(2)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:survey_id, :response)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show ]

  # GET /surveys or /surveys.json
  def index
    @survey_stats = []
    @surveys = Survey.all

    @surveys.each_with_index do |survey, i|
      stats = {}
      stats[:survey] = survey
      stats[:question] = survey.question
      stats[:count] = survey.answers.count()
      stats[:yes] = result_percentage(survey, 1)
      stats[:no] = result_percentage(survey, 0)
      @survey_stats << stats
    end
  end

  def result_percentage(survey, response)
    total = survey.answers.count()
    count = survey.answers.where(response: response).count()
    (count.to_f / total.to_f).round(2) * 100
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:question)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p>
    <strong>Response:</strong>
    <%= answer.response %>
  </p>

</div>

app/views/answers/_form.html.erb
<%= form_with(model: answer) do |form| %>
  <% if answer.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
        <% answer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :response, style: "display: block" %>
    <%= form.check_box :response %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<!--<h1>Editing answer</h1>-->

<%#= render "form", answer: @answer %>

<!--<br>-->

<!--<div>-->
<!--  <%#= link_to "Show this answer", @answer %> |-->
  <%#= link_to "Back to answers", answers_path %>
<!--</div>-->

app/views/answers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Answers</h1>

<div id="answers">
  <% @answers.each do |answer| %>
    <%= render answer %>
    <p>
      <%= link_to "Show this answer", answer %>
    </p>
  <% end %>
</div>

<%= link_to "New answer", new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render "form", answer: @answer %>

<br>

<div>
  <%= link_to "Back to answers", answers_path %>
</div>

app/views/answers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @answer %>

<div>
  <%= link_to "Edit this answer", edit_answer_path(@answer) %> |
  <%= link_to "Back to answers", answers_path %>

  <%= button_to "Destroy this answer", @answer, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppleSurvery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_with(model: survey) do |form| %>
  <% if !survey.nil? && survey.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :question, style: "display: block" %>
    <%= form.text_field :question %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/_survey.html.erb
<div id="<%= dom_id survey %>">
  <h3><%= survey.question %></h3>
</div>

app/views/surveys/edit.html.erb
<!--<h1>Editing survey</h1>-->

<%#= render "form", survey: @survey %>

<!--<br>-->

<!--<div>-->
<!--  <%#= link_to "Show this survey", @survey %> |-->
  <%#= link_to "Back to surveys", surveys_path %>
<!--</div>-->

app/views/surveys/index.html.erb
<p style="color: green"><%= notice %></p>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<h1>Surveys</h1>

<div id="surveys">
  <table>
    <tr>
      <th>Question</th>
      <th>Answer Count</th>
      <th>Percent YES</th>
      <th>Percnet NO</th>
    </tr>
    <% @survey_stats.each do |survey_stat| %>
      <tr>
        <td><%= link_to survey_stat[:question], survey_stat[:survey] %></td>
        <td><%= survey_stat[:count] %></td>
        <td><%= survey_stat[:yes] %></td>
        <td><%= survey_stat[:no] %></td>
      </tr>
    <% end %>
  </table>
</div>

<p>
  <%= button_to "New survey", new_survey_path, :method => :get %>
</p>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render "form", survey: @survey %>

<br>

<div>
  <%= link_to "Back to surveys", surveys_path %>
</div>

app/views/surveys/show.html.erb
<p style="color: green"><%= notice %></p>

<table>
  <tr>
    <td><%= render @survey %></td>

    <td><%= button_to "Yes",
                      action: "create",
                      controller: "answers",
                      survey_id: @survey.id,
                      response: true
    %></td>

    <td><%= button_to "No",
                      action: "create",
                      controller: "answers",
                      survey_id: @survey.id,
                      response: false
    %></td>
  </tr>
</table>

<div>
  <p>
    <%= link_to "Back to surveys", surveys_path %>
  </p>
</div>